cache:
  bundler: true
  directories:
    - node_modules
language: node_js
node_js:
- '6'
script:
- mkdir build && zip -y -q -1 -r build/build.zip *
deploy:
  - provider: s3
    access_key_id: AKIAIGPDK3FVZYDY2Q6A
    secret_access_key:
      secure: "i3U+T7XgQyH3M77WI5rjAMJf6whVb4XqAqLLr3klfhXjR2rHd1a5rS7es8ggGxrCiBcCVBTxgfmx0c2mb8rDybtrOgavvg7rCIP500/a/9/nJu7ZoSJUHXkZBXWcPbGOBfniFtAQXfBfD4DqAZuPKQoKKSuvLDuAFktXokhUD5URxWivcBWCM56jwOnuoZ77RtGo7sYQQ+svc+3v9cglfZcfY6Xt0Fx+7+ssgyJTTv+XH7C5/y751weqdK0co9kg3zSpHMtMAG+57qpOTSLm8boap2OZqVAdTEclaGPX7yu54WsSPSp1onxknyedg9l9q3afT6m4+2yNUfjJ+AZAhWMgGi1VnWzs+DVWUTcIv9+y1EAJ4NBebk6K94kLns9fLVaEGT+Dxfthl7uNVz2wd3sonHYhu9nJUQc3O70VdLN2eKZOrs7MkWp6A9q8q4kUia86JLqmxT1VWVVNI199KTNpME8Sn330Ambh8EZ6+H7vG/v1lSpjIZXGjgMD7jp1CMakaeb/0u5I1uzeJTNIsKViUAq0IdTr2SA/RXQmqAA28l9aj++d9MBmR3hzuugSGkqqXjzzS726d4UN8SPX2IlaI+81clKKxjJ+u1MzaQ8eRRIoRcAh9nB7LOvsdypMyurrW3x4OQz5HrOh5x1emlUGEyZdumKIkXTBZMzLcm8="
    bucket: event-loop-js
    skip_cleanup: true
    upload-dir: master
    local_dir: build
    region: us-east-1
    on:
      branch: master
  - provider: codedeploy
    access_key_id: AKIAIGPDK3FVZYDY2Q6A
    secret_access_key:
      secure: "i3U+T7XgQyH3M77WI5rjAMJf6whVb4XqAqLLr3klfhXjR2rHd1a5rS7es8ggGxrCiBcCVBTxgfmx0c2mb8rDybtrOgavvg7rCIP500/a/9/nJu7ZoSJUHXkZBXWcPbGOBfniFtAQXfBfD4DqAZuPKQoKKSuvLDuAFktXokhUD5URxWivcBWCM56jwOnuoZ77RtGo7sYQQ+svc+3v9cglfZcfY6Xt0Fx+7+ssgyJTTv+XH7C5/y751weqdK0co9kg3zSpHMtMAG+57qpOTSLm8boap2OZqVAdTEclaGPX7yu54WsSPSp1onxknyedg9l9q3afT6m4+2yNUfjJ+AZAhWMgGi1VnWzs+DVWUTcIv9+y1EAJ4NBebk6K94kLns9fLVaEGT+Dxfthl7uNVz2wd3sonHYhu9nJUQc3O70VdLN2eKZOrs7MkWp6A9q8q4kUia86JLqmxT1VWVVNI199KTNpME8Sn330Ambh8EZ6+H7vG/v1lSpjIZXGjgMD7jp1CMakaeb/0u5I1uzeJTNIsKViUAq0IdTr2SA/RXQmqAA28l9aj++d9MBmR3hzuugSGkqqXjzzS726d4UN8SPX2IlaI+81clKKxjJ+u1MzaQ8eRRIoRcAh9nB7LOvsdypMyurrW3x4OQz5HrOh5x1emlUGEyZdumKIkXTBZMzLcm8="
    bucket: event-loop-js
    key: master/build.zip
    application: EventLoopJS
    deployment_group: MASTER
    region: us-east-1
    on:
      branch: master
  
