cache:
  bundler: true
  directories:
    - node_modules
language: node_js
node_js:
- '6'
script:
- mkdir build && zip -y -q -1 -r build/build.zip *
deploy:
  - provider: s3
    access_key_id: AKIAJ2CI6Y3F5AUY5ZMQ
    secret_access_key:
      secure: "ub6eGaeJJMt9dDLEkoCpYDkzR8QruucxumWZ/w7pyMVMd/H/DihqKwcd8gl498TuTRixKm95Q130acKGcCmOW2ZaOc0iJdzPETyKM94lqO+2UfHsHXwNCTJbGQOJuqcWaYu7eItNdCSsHNgp4nVIPuZXRlLzhcspOs5gr2VKkXmSMUmkSGzidGYBdRVIWBIbJaDBvX8aOJMog+lhDKsTabaElmCY+FQHST2Wvd4bOdz/Nx3A0AexkKYL/Y7BbXLp42yqi1T7evarqrIQaRfZFP3wvmogdrkpaDJkmKLsnvvVXiBCcGQWgkGQBK+8GcO8plp3MOI8h6RXlyw7N4HojtjWa1BZos16vbAAp2xRbZ0oNiGfA3wWy+NlBxmw3CpYmuIQ61OxhUnczcsBRvWvRcTFOlsWLw0wGPHHSymhfw9d7AXJTyDf1Mym2EUytF9LFrRd+9WIygbICsOf5t2b4AEpePc6LUYgiFaafLzqvCjLKsoZOwB5VCTvrYNagfvHum41QE/cRx51+OZJ4ihJANLRYmLOXPKC8izguc5U6v46U3OZvToVg2QcLfqKogAqiORrqxsPM5sg/CXbEp9WvBi9JEWLcSfTGEm60W4hO88AP+OnDBuyvG8espG7tfXxAcoVwEnd0lpGrSOdqm2gJ2IvrqwfEJ8REPrYG+NsSws="
    bucket: event-loop-js
    skip_cleanup: true
    upload-dir: master
    local_dir: build
    region: us-east-1
    on:
      branch: master
  - provider: codedeploy
    access_key_id: AKIAJ2CI6Y3F5AUY5ZMQ
    secret_access_key:
      secure: "ub6eGaeJJMt9dDLEkoCpYDkzR8QruucxumWZ/w7pyMVMd/H/DihqKwcd8gl498TuTRixKm95Q130acKGcCmOW2ZaOc0iJdzPETyKM94lqO+2UfHsHXwNCTJbGQOJuqcWaYu7eItNdCSsHNgp4nVIPuZXRlLzhcspOs5gr2VKkXmSMUmkSGzidGYBdRVIWBIbJaDBvX8aOJMog+lhDKsTabaElmCY+FQHST2Wvd4bOdz/Nx3A0AexkKYL/Y7BbXLp42yqi1T7evarqrIQaRfZFP3wvmogdrkpaDJkmKLsnvvVXiBCcGQWgkGQBK+8GcO8plp3MOI8h6RXlyw7N4HojtjWa1BZos16vbAAp2xRbZ0oNiGfA3wWy+NlBxmw3CpYmuIQ61OxhUnczcsBRvWvRcTFOlsWLw0wGPHHSymhfw9d7AXJTyDf1Mym2EUytF9LFrRd+9WIygbICsOf5t2b4AEpePc6LUYgiFaafLzqvCjLKsoZOwB5VCTvrYNagfvHum41QE/cRx51+OZJ4ihJANLRYmLOXPKC8izguc5U6v46U3OZvToVg2QcLfqKogAqiORrqxsPM5sg/CXbEp9WvBi9JEWLcSfTGEm60W4hO88AP+OnDBuyvG8espG7tfXxAcoVwEnd0lpGrSOdqm2gJ2IvrqwfEJ8REPrYG+NsSws="
    bucket: event-loop-js
    key: master/build.zip
    application: EventLoopJS
    deployment_group: MASTER
    region: us-east-1
    on:
      branch: master
  
