cache:
  bundler: true
  directories:
    - node_modules
language: node_js
node_js:
- '6'
script:
- npm test
- mkdir build && zip -y -q -1 -r build/build.zip *
deploy:
  - provider: s3
    access_key_id: AKIAIBURBMH5A3ETKRVQ
    secret_access_key:
      secure: "qlPoVXtcztxuWE8hClGU/wS/dZcI4ZR5C+yXYDIOW35SQVCU0Vqo5Y2yytOx/1EMb1TghH6eF1m+QlrS51E35v945pJOm6Ya5qSvo8Xlln4kzS87kTCKxRU8C7wyugpMsSGGlnXoWguq1NPrJrL1JK9+5htaeuO9rXC3FAnovLshz8OgWwe6oFTkFsDhxpjAIAxlHi/CF4b2QT9wBzYE+VZ1PUOAPk088S4/PPBZ49KiZxob6tw6mL3EbC6s/OavsA+qEQvinemVS+Z/NQi3fwxbC1dJ3qSod1BYW+Iy4Mo4M6/8C1zEUhAjCFo70MBetX3LSOMUH5IB9ZKvItG5WfWgtFgkkYvHbOh0gCZTPVWl8eYQS0Cpb8q1s5UV6TKgAUuB/9iU9gKv4sV6uKBuiITME4TTLJzJuNVV4/T2S7lCn3jRriIcFqBRHe8DJBDbLeMnR2T4RvViBi1mqV65+bn0Jl6Ozwe40K+nsAq/slMsGKES2Vz8GcNErr3YOjgR2s3cuPWG8tP112s1txDDOYnkR7IaH3uELYGEVdW7kjCCcwedpKk84n28so56K5MjXfNPd0waUCQztvtjGD8VBqDSosL17TwdiLcGGHt3fZYIHwCScOjY/syIdBHRRUK0SVw3nAHGoZDnGNGpreFTmRxsK7VyZZhkicczekvTprY="
    bucket: event-loop-js
    skip_cleanup: true
    upload-dir: master
    local_dir: build
    region: us-east-1
    on:
      branch: master
  - provider: codedeploy
    access_key_id: AKIAIBURBMH5A3ETKRVQ
    secret_access_key:
      secure: "qlPoVXtcztxuWE8hClGU/wS/dZcI4ZR5C+yXYDIOW35SQVCU0Vqo5Y2yytOx/1EMb1TghH6eF1m+QlrS51E35v945pJOm6Ya5qSvo8Xlln4kzS87kTCKxRU8C7wyugpMsSGGlnXoWguq1NPrJrL1JK9+5htaeuO9rXC3FAnovLshz8OgWwe6oFTkFsDhxpjAIAxlHi/CF4b2QT9wBzYE+VZ1PUOAPk088S4/PPBZ49KiZxob6tw6mL3EbC6s/OavsA+qEQvinemVS+Z/NQi3fwxbC1dJ3qSod1BYW+Iy4Mo4M6/8C1zEUhAjCFo70MBetX3LSOMUH5IB9ZKvItG5WfWgtFgkkYvHbOh0gCZTPVWl8eYQS0Cpb8q1s5UV6TKgAUuB/9iU9gKv4sV6uKBuiITME4TTLJzJuNVV4/T2S7lCn3jRriIcFqBRHe8DJBDbLeMnR2T4RvViBi1mqV65+bn0Jl6Ozwe40K+nsAq/slMsGKES2Vz8GcNErr3YOjgR2s3cuPWG8tP112s1txDDOYnkR7IaH3uELYGEVdW7kjCCcwedpKk84n28so56K5MjXfNPd0waUCQztvtjGD8VBqDSosL17TwdiLcGGHt3fZYIHwCScOjY/syIdBHRRUK0SVw3nAHGoZDnGNGpreFTmRxsK7VyZZhkicczekvTprY="
    bucket: event-loop-js
    key: master/build.zip
    application: EventLoopJS
    deployment_group: MASTER
    region: us-east-1
    wait-until-deployed: true
    on:
      branch: master
  
