cache:
  bundler: true
  directories:
    - node_modules
language: node_js
node_js:
- '6'
script:
- mkdir build && zip -y -q -1 -r build/build.zip *
deploy:
  - provider: s3
    access_key_id: AKIAIWQCT23FR73PR6OA
    secret_access_key:
      secure: XNy2N+pV1tox2TtnyeHiwdKWXrous600UUX9CHk0aB8x4bukQ8zdg3yJIn5/gvHodUcU5pc3LW5WAdshz6cPJaj2GVVBiVZRGr9PUBBmLTE5icaXF2q3j+y0p/8Kt4OUPiqwzPF5xRyTa2I3NN/1wGzNeZMssa/YtIE8TcJW7HQLaaL7f4p8xtj6eEdXNVufeOmmIWI9wvPO2yZKfguGff2dBaA/FkEvCfTRNEX1DQeiDwJJe+xpEP/PlMtYkW/PGYpCFq9fdntfhcmG5evHkFyMqi5Ko7Vb479StkekwRWBBlciX3Su+N0oYtO11uAKcEnQo5n/iZ9r90F7kThzduPhJqkZcsHZDPoTwpAg2x6PmOX0ZOBvjljQIV5IbKzl84Ux/vZ4r0sSsGRrUCod15VswHnioHBZ+7oafmWd1PHEEbHjmf++VR4p8sXcadP+CzW65/lcCLS9QT3qthZaf1Rjh1Wt57Ihi2knijsfghLy7nClQG1wCKkrWBMiM35A/myV2neY3J51mip4c5jhlCuEojxhFsZ/z7N8KVX8e/ROBit6PrESD50lAXv30az9G3Jc+WHsxbqV5DGOHIHX3PS+IKSwkWLyR6bTgJ4BKLgefeHIFstfdUZCwyARgfuJxQwOM0TTUfF41BHPEMxHcTNKItHBRFfbPx786o4RKKA=
    bucket: event-loop-js
    skip_cleanup: true
    upload-dir: master
    local_dir: build
    region: us-east-1
    on:
      branch: master
  - provider: codedeploy
    access_key_id: AKIAIWQCT23FR73PR6OA
    secret_access_key:
      secure: XNy2N+pV1tox2TtnyeHiwdKWXrous600UUX9CHk0aB8x4bukQ8zdg3yJIn5/gvHodUcU5pc3LW5WAdshz6cPJaj2GVVBiVZRGr9PUBBmLTE5icaXF2q3j+y0p/8Kt4OUPiqwzPF5xRyTa2I3NN/1wGzNeZMssa/YtIE8TcJW7HQLaaL7f4p8xtj6eEdXNVufeOmmIWI9wvPO2yZKfguGff2dBaA/FkEvCfTRNEX1DQeiDwJJe+xpEP/PlMtYkW/PGYpCFq9fdntfhcmG5evHkFyMqi5Ko7Vb479StkekwRWBBlciX3Su+N0oYtO11uAKcEnQo5n/iZ9r90F7kThzduPhJqkZcsHZDPoTwpAg2x6PmOX0ZOBvjljQIV5IbKzl84Ux/vZ4r0sSsGRrUCod15VswHnioHBZ+7oafmWd1PHEEbHjmf++VR4p8sXcadP+CzW65/lcCLS9QT3qthZaf1Rjh1Wt57Ihi2knijsfghLy7nClQG1wCKkrWBMiM35A/myV2neY3J51mip4c5jhlCuEojxhFsZ/z7N8KVX8e/ROBit6PrESD50lAXv30az9G3Jc+WHsxbqV5DGOHIHX3PS+IKSwkWLyR6bTgJ4BKLgefeHIFstfdUZCwyARgfuJxQwOM0TTUfF41BHPEMxHcTNKItHBRFfbPx786o4RKKA=

    bucket: event-loop-js
    key: master/build.zip
    application: EvenLoopJS
    deployment_group: MASTER
    region: us-east-1
    on:
      branch: master
  
