language: "node_js"
node_js:
  - "6"
script:
  - mkdir build && zip -q -1 -r build/build.zip *
deploy: 
  - 
    provider: s3
    access_key_id: AKIAIKAZ6UDABJNLX3QQ
    bucket: event-loop-js-s3
    secret_access_key: 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
    skip_cleanup: true
    on:
      branch: master
    local_dir: build
    region: eu-west-1
